---
title: "팀프로젝트_3조"
author: "LSH"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [데이터 분석 개요]
### 1. 대상 데이터: 밀링 기계 데이터셋
(https://www.kaggle.com/datasets/shivamb/machine-predictive-maintenance-classification)

- UID : 1~10000 범위의 고유 식별자
- product ID : 제품 일련번호
- Type : 제품 품질 (H, M, L)
- Air temperature : 
- Process temperature :
- Rotational speed : RPM
- Torque : 토그 값
- Tool wear : Tool 마모(사용시간), 생산된 제품 품질마다 시간 구분 (H:5min, M:3min, L:2min)
- Target : Failure or Not
- Failure Type : Tpye of Failure

<br>
<br>
<br>

### 1. 데이터 탐색 (EDA) 및 전처리
```{r preprocess}
dat <- read.csv('predictive_maintenance.csv')
str(dat)

# column 이름 변경
colnames(dat) <- gsub('[.]','_',colnames(dat))
colnames(dat) <- gsub('_+','_',colnames(dat))
colnames(dat) <- gsub('_$','',colnames(dat))
colnames(dat)

# 데이터 요약 정보
summary(dat)

# UID, ProductID 변수 삭제
dat <- dat[,-c(1,2)]
colnames(dat)

# 변수 Type 변경
dat$Target <- as.character(dat$Target)

# 결측치 확인 (True : 결측치, False : 정상)
table(is.na(dat))

# 데이터 시각화
library(ggplot2)
library(gridExtra)
library(dplyr)

# Type Column Data
table(dat$Type)

type_counts <- dat %>% 
  count(Type) %>% 
  mutate(perc = n / sum(n) * 100)

ggplot(type_counts, aes(x = "", y = perc, fill = Type)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(label = paste0(round(perc, 1), "%")), 
            position = position_stack(vjust = 0.5)) +
  ggtitle("Type Distribution") +
  theme(plot.title = element_text(hjust = 0.5))

# Target & Failure Type Column Data (0 : No Fail, 1 : Fail)
table(dat$Target)
table(dat$Failure_Type)

# Target Column의 0(No Fail) 갯수와 Failure_type Column의 No Failure 갯수 차이 존재.
# 이상치 제거 (Target 값과 Failure Type의 내용과 일치하지 않는 데이터 제거)
# 'Target'이 1이면서 'FailureType'이 'No Failure'인 행 제거
dat <- dat[!(dat$Target == "1" & dat$Failure_Type == "No Failure"),]
# 'Target'이 0이면서 'FailureType'이 'No Failure'가 아닌 행 제거
dat <- dat[!(dat$Target == "0" & dat$Failure_Type != "No Failure"),]

# 이상치 제거 여부 확인
table(dat$Target)
table(dat$Failure_Type)

# Failure Type Column Data
F_type_counts <- dat %>% 
  filter(Failure_Type != "No Failure") %>%
  count(Failure_Type) %>% 
  mutate(perc = n / sum(n) * 100)

ggplot(F_type_counts, aes(x = "", y = perc, fill = Failure_Type)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(label = paste0(round(perc, 1), "%")), 
            position = position_stack(vjust = 0.5)) +
  ggtitle("Failure Type Distribution") +
  theme(plot.title = element_text(hjust = 0.5))

# Numerical, Integer Column 시각화
visualize <- function(x){
    ggplot() + geom_histogram(aes(x), color="white")
}

g_air_temp <- visualize(dat[,2]) + xlab(colnames(dat)[2])
g_proc_temp <- visualize(dat[,3]) + xlab(colnames(dat)[3])
g_rpm <- visualize(dat[,4]) + xlab(colnames(dat)[4])
g_torq <- visualize(dat[,5]) + xlab(colnames(dat)[5])
g_tool_wear <- visualize(dat[,6]) + xlab(colnames(dat)[6])

grid.arrange(g_air_temp, g_proc_temp, g_rpm, g_torq, g_tool_wear, ncol = 3)
```
### 2. 가설 설정 및 검정
```{r hypothesis}

## 1. 제품 별 품질타입 L,M,H(각각 50,30,20%)의 차이 분석

# 가설설정 - Air_temperature의 평균
# H0: L, M, H 타입간 Air_temperature의 평균에 차이가 없다.
# H1: L, M, H 타입간 Air_temperature의 평균에 차이가 있다.

# 3수준 이상이므로 ANOVA 활용

anova_air <- aov(Air_temperature_K ~ Type, data = dat)
summary(anova_air)

# p-value가 유의수준인 0.05보다 크므로 귀무가설 기각 불가
# => 평균 차이가 유의하지 않음

# 타입별 분포 시각화(Boxplot)
{ ggplot(dat, aes(x = Type, y = Air_temperature_K)) +
  geom_boxplot() +
  labs(title = "Box Plot of Air Temperature by Type",
       x = "Type",
       y = "Air Temperature (K)") +
  theme_minimal() }



# 가설설정 - Process_temperature의 평균
# H0: L, M, H 타입간 Process_temperature의 평균에 차이가 없다.
# H1: L, M, H 타입간 Process_temperature의 평균에 차이가 있다.

anova_process <- aov(Process_temperature_K ~ Type, data = dat)
summary(anova_process)

# p-value가 유의수준인 0.05보다 크므로 귀무가설 기각 불가
# => 평균 차이가 유의하지 않음

# 타입별 분포 시각화(Boxplot)
{ ggplot(dat, aes(x = Type, y = Process_temperature_K)) +
  geom_boxplot() +
  labs(title = "Box Plot of Process Temperature by Type",
       x = "Type",
       y = "Process Temperature (K)") +
  theme_minimal() }



# 가설설정 - Rotational_speed의 평균
# H0: L, M, H 타입간 Rotational_speed의 평균에 차이가 없다.
# H1: L, M, H 타입간 Rotational_speed의 평균에 차이가 있다.

anova_rot <- aov(Rotational_speed_rpm ~ Type, data = dat)
summary(anova_rot)

# p-value가 유의수준인 0.05보다 크므로 귀무가설 기각 불가
# => 평균 차이가 유의하지 않음

# 타입별 분포 시각화(Boxplot)
{ ggplot(dat, aes(x = Type, y = Rotational_speed_rpm)) +
  geom_boxplot() +
  labs(title = "Box Plot of Rotational speed by Type",
       x = "Type",
       y = "Rotational speed (RPM)") +
  theme_minimal() }

# => ㅣ타입의 군내 수가 많아서 이상치 수 또한 많은 것으로 보임. 향후 추가 분석 필요



# 가설설정 - Torque의 평균
# H0: L, M, H 타입간 Torque의 평균에 차이가 없다.
# H1: L, M, H 타입간 Torque의 평균에 차이가 있다.

anova_torque <- aov(Torque_Nm ~ Type, data = dat)
summary(anova_torque)

# p-value가 유의수준인 0.05보다 크므로 귀무가설 기각 불가
# => 평균 차이가 유의하지 않음

# 타입별 분포 시각화(Boxplot)
{ ggplot(dat, aes(x = Type, y = Torque_Nm)) +
  geom_boxplot() +
  labs(title = "Box Plot of Torque by Type",
       x = "Type",
       y = "Torque (Nm)") +
  theme_minimal() }


# 가설설정 - Tool_wear의 평균
# H0: L, M, H 타입간 Tool_wear의 평균에 차이가 없다.
# H1: L, M, H 타입간 Tool_wear의 평균에 차이가 있다.

anova_tw <- aov(Tool_wear_min ~ Type, data = dat)
summary(anova_tw)

# p-value가 유의수준인 0.05보다 크므로 귀무가설 기각 불가
# => 평균 차이가 유의하지 않음

# 타입별 분포 시각화(Boxplot)
{ ggplot(dat, aes(x = Type, y = Tool_wear_min)) +
  geom_boxplot() +
  labs(title = "Box Plot of Tool wear by Type",
       x = "Type",
       y = "Tool wear") +
  theme_minimal() }


```

### 3. 모델 생성
```{r model}

## 2. 각 변수별 상관관계 확인 및 주성분 추출

# 변수간 상관계수 도출(히트맵)


## 3. 고장 예측(+유형 분류) 모델 제작

# 3-1. Random Forest

# 3-2. SVM

# 3-3. ???


## 4. 모델 평가 및 개선

